//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class register
    {
        public int Rid { get; set; }
        [Required(ErrorMessage = "field required")]
        public string fname { get; set; }
        [Required(ErrorMessage="field required")]
        public string lname { get; set; }
        [Required(ErrorMessage = "Fiel required")]
        public string username { get; set; }
        [Required(ErrorMessage = "Fiel required")]
        public string address { get; set; }
        [Required(ErrorMessage = "Fiel required")]
        public Nullable<int> phone { get; set; }
        [Required(ErrorMessage="field required")]
        public Nullable<bool> Isadmin { get; set; }
        [Required(ErrorMessage = "field required")]
        [DisplayName("Upload File")]
        public string photo { get; set; }
        [Required(ErrorMessage = "field required")]
        public HttpPostedFileWrapper ImageFile { get; set; }
        [DataType(DataType.Password)]
        public string password { get; set; }
        [DisplayName("conform password")]
        [Compare("password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "field required")]
        public string cpassword { get; set; }
    }
}
